#!/bin/bash

source $(dirname -- "$0")/bootstrap
options=$(options "" "index type documentId documentJson")

index="$1"
type="$2"
documentId="$3"
documentJson="$4"

# example document json: {"identity": {"name": "ruan", "surname": "bekker"}}

elastic_put "$index/$type/$documentId" -d \'$documentJson\'