#!/bin/bash

source $(dirname -- "$0")/bootstrap
options=$(options "pretty" "index term size")

index="$1"
term="$2"
size="$3"

elastic_get "$index/_search$options" -d \'
{
  "query": {
    "term": {
      "title": "$term"
    }
  }, 
  "size": $size
}
\'