#!/bin/bash

source $(dirname -- "$0")/bootstrap
options=$(options "" "index numberOfReplicas")

index="$1"
numberOfReplicas="$2"

elastic_put "$index"/_settings -d '{"settings": {"index": {"number_of_replicas": '"$numberOfReplicas"'}}}'