#!/bin/bash

ui="${1:-cli}"

if [ "$ui" == "cli" ]
then
    source lib/ui-cli
else
    source lib/ui-gui
fi


func_cluster_health() {
    showInfo "Cluster Health" "$(./cluster-health 2>/dev/null)"
}

func_info_master() {
    ./info-master
}

declare -A MENU_MAIN=(
    [MENU_CLUSTERS]="clusters"
    [MENU_DOCUMENTS]="documents"
    [MENU_INDICES]="indices"
    [MENU_SHARDS]="shards"
    [FUNC_CLUSTER_HEALTH]="cluster health"
    [FUNC_INFO_MASTER]="master info"
)

declare -A MENU_CLUSTERS=(
    [FUNC_CLUSTER_HEALTH]="cluster health"
    [FUNC_CLUSTER_HEALTH_INDEX_LEVEL]="index level"
    [FUNC_CLUSTER_HEALTH_SHARDS_LEVEL]="shards level"
)

# showGUIDialog() {
#     zenity --title "ElasticSearch" --list --hide-column=1 --column="id" --column="choice" 0 dog 1 cat 2 dogcat
# }

displayMenu() {
    # the name of the menu
    menuName="$1"
    # menu contains the name of the menu to load
    declare -n menu="$menuName"
    # optionsArray contains a numerically indexed list of option names for display in menu
    declare -a optionsArray=()
    # targetsArray contains a numerically indexed list of target names
    declare -a targetsArray=()

    # create optionsArray and targetArray as numerically indexed
    # projections of 'menu'
    ((count=0))
    for id in "${!menu[@]}"
    do
        optionsArray[$count]="${menu[$id]}"
        targetsArray[$count]="$id"

        (( count+=1 ))
    done
    # options is the string we'll send to the dialog apps
    options=""
    for id in "${!optionsArray[@]}"
    do
        name="${optionsArray[$id]}"
        options="$options $id \"$name\""
    done

    # show the menu and get the response
    selection=$(showMenu "$options")

    # cancel was selected
    if [ -z "$selection" ]; then
        exit
    fi

    # target path
    targetPath="${targetsArray[$selection]}"

    if [[ "$targetPath" =~ ^FUNC ]]
    then
        eval ${targetPath,,}
        displayMenu "$menuName"
    elif [[ "$targetPath" =~ ^MENU ]]
    then
        displayMenu "$targetPath"
    else
        echo "unknown selection target"
        exit
    fi
}

displayMenu "MENU_MAIN"