#!/bin/bash

source $lib/curl

hostUrl=${ELASTICSEARCH_HOST:-"http://0.0.0.0:9200"}

elastic_get() {
    path="$1"
    curl_call GET $hostUrl/$path
}

elastic_post() {
    path="$1"
    curl_call POST $hostUrl/$path
}

elastic_put() {
    path="$1"
    curl_call PUT $hostUrl/$path
}

elastic_delete() {
    path="$1"
    curl_call DELETE $hostUrl/$path
}